[package]
name = "rust-crate-scanner"
version = "0.0.0"
edition = "2018"

[[bin]]
name = "rust-crate-scanner"
path = "main.rs"

[dependencies]
cargo-lock = "7.0.1"
serde_json = "1.0"
cargo_toml = "0.20.4"
toml = "0.5.8"
serde = { version = "1.0.130", features = ["derive"] }
