name: CI
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test-web:
    timeout-minutes: 10
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.4.4
        with:
          version: 16.14.1
      - run: npm install -g yarn@1.22.19
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn typecheck
