name: CI
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v3.5.1
        with:
          version: 14.21.0
      - name: Install prerequisites
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y binutils
          command -v readelf
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn typecheck
      - run: yarn test
