name: CI
on:
  pull_request:
  push:
    branches:
      - master
      - rzadp/debug

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3.3.0
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v3.5.1
        with:
          node-version-file: '.nvmrc'
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn build
      - run: cargo build --release
        working-directory: rust-crate-scanner
      - run: yarn test
  e2e:
    timeout-minutes: 10
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3.3.0
        with:
          path: license-scanner
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v3.5.1
        with:
          node-version-file: 'license-scanner/.nvmrc'
      - uses: actions/checkout@v3.3.0
        with:
          repository: paritytech/polkadot
          ref: '1c935f35139f3f43cb22009dc5c010dfbe6ad9e7'
          path: polkadot
      - run: yarn install --frozen-lockfile
        working-directory: license-scanner
      - name: Build and install globally
        run: |
          yarn build
          npm i -g .
        working-directory: license-scanner
      - name: Debug
        run: |
          which license-scanner
          which node
          node --version
          /usr/bin/env node --es-module-specifier-resolution=node --version
          ls -al /opt/hostedtoolcache/node/16.19.0/x64/bin/
        working-directory: polkadot
      - name: Scan the Polkadot repo - absolute
        run: |
          node /opt/hostedtoolcache/node/16.19.0/x64/lib/node_modules/@paritytech/license-scanner/build/license-scanner/main.js scan --log-level debug ./node
        working-directory: polkadot
        timeout-minutes: 3
      - name: Scan the Polkadot repo - node directory
        run: |
          DEBUG=1 license-scanner scan --log-level debug ./node
        working-directory: polkadot
        # It should take a reasonable time to scan the node crate.
        timeout-minutes: 3
      - name: Dump into csv
        working-directory: polkadot
        run: |
          license-scanner dump csv $(realpath ./node) ./output.csv
          # Check a couple of rows to make sure we have the output we expected.
          grep -q '"metrics/src/lib.rs","GPL-3.0-only"' ./output.csv
          grep -q '"overseer/src/tests.rs","GPL-3.0-only"' ./output.csv
      - name: Enforce licenses in Rust files
        run: |
          shopt -s globstar

          license-scanner scan \
            --log-level debug \
            --ensure-licenses Apache-2.0 \
            --ensure-licenses GPL-3.0-only \
            --exclude ./**/target ./**/weights \
            --include ./**/src/**/*.rs \
            && exit 1 || exit 0
            # We expected it to fail because there are some unlicensed files left.
        working-directory: polkadot
