name: CI
on:
  pull_request:
  push:
    branches:
      - master
      - rzadp/scanning-features-cont

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3.3.0
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v3.5.1
        with:
          version: 14.21.0
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn build
      - run: cargo build --release
        working-directory: rust-crate-scanner
      - run: yarn test
  e2e:
    timeout-minutes: 10
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3.3.0
        with:
          path: license-scanner
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v3.5.1
        with:
          version: 14.21.0
      - uses: actions/checkout@v3.3.0
        with:
          repository: paritytech/polkadot
          ref: '1c935f35139f3f43cb22009dc5c010dfbe6ad9e7'
          path: polkadot
      - run: yarn install --frozen-lockfile
        working-directory: license-scanner
      - run: yarn build
        working-directory: license-scanner
      - name: Scan the Polkadot repo
        run: |
          yarn start -- scan --log-level debug ../polkadot/node
        working-directory: license-scanner
        # It should take a reasonable time to scan the node crate.
        timeout-minutes: 3
      - name: Enforce licenses in Rust files
        run: |
          yarn start -- scan \
            --log-level debug \
            --ensure-licenses Apache-2.0 \
            --ensure-licenses GPL-3.0-only \
            --exclude ../polkadot/**/target ../polkadot/**/weights
            ../polkadot/**/src/**/*.rs \
            && exit 0 || exit 1
            # The command is expected to fail because there are some unlicensed files left.
        working-directory: license-scanner
